version: '3'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:4.2.0'
    ports:
      - 27017:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=my_password
      - MONGODB_DATABASE=my_database
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary


  mongodb-secondary-1:
    image: 'bitnami/mongodb:4.2.0'
    ports:
      - 27018:27017
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary-1

  mongodb-secondary-2:
    image: 'bitnami/mongodb:4.2.0'
    ports:
      - 27019:27017
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary-2
  
  mongodb-arbiter:
    image: 'bitnami/mongodb:4.2.0'
    ports:
      - 27020:27017
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter

networks:
  default:
    external:
      name: local-net
